<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>Pace_Note_Generator</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Frontend\Transparent Background.png" />
    <None Remove="Transparent Background.png" />
  </ItemGroup>

  <ItemGroup>
    <Page Remove="Frontend\App.xaml" />
  </ItemGroup>

  <ItemGroup>
    <ApplicationDefinition Include="Frontend\App.xaml" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Frontend\Transparent Background.png" />
  </ItemGroup>

</Project>
